# Environmental parameters for freshwater in Trondheim, Norway
#
# Gravity value from EGM2008 12th order via wolframalpha.com
# Pressure value from 10 year average via wolframalpha.com

atmosphere:
  pressure: 101500

water:
  density: 1000 # Freshwater
  # density: 1025 # Saltwater

gravity:
  acceleration: 9.79609
